[package]
name = "binance-async"
version = "0.2.0"
edition = "2018"
license = "MIT OR Apache-2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>", "Weiyüen Wu <doomsplayer@gmail.com>"]

description = "Rust Library for the Binance API (Async)"
keywords = ["cryptocurrency", "trading", "binance", "async"]
documentation = "https://docs.rs/crate/binance-async"
repository = "https://github.com/dovahcrow/binance-async-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "dovahcrow/binance-async-rs" }

[lib]
name = "binance_async"
path = "src/lib.rs"

[dependencies]
failure = "0.1"
log = "0.4"
sugar = "0.2"

tungstenite = "0.6"
tokio-tungstenite = "0.6"

url = "1"
futures01 = { package = "futures", version = "0.1" }
futures-preview = { version = "0.3.0-alpha", features = ["compat"] }
headers = "0.2"
http = "*"
reqwest = { version = "0.10.0-alpha", features = ["json"] }
reqwest-ext = { git = "https://github.com/vorot93/reqwest-ext" }
tokio = "0.2.0-alpha"
tokio01 = { package = "tokio", version = "0.1" }

chrono = { version = "0.4", features = ["serde"] }

serde = "1"
serde_json = "1"
serde_derive = "1"

hex = "0.3"
sha2 = "0.8"
hmac = "0.7"

[dev-dependencies]
csv = "1"
dotenv = "0.13"
env_logger = "0.5"